### ISSUE TITLE
Internal Error during test collection with pytest and teamcity-messages plugin

### ISSUE THREAD

**Issue by rabodaber** [JetBrains/teamcity-messages#112]
When running with 16 threads with xdist some threads collect less tests with exception:

```
[23:35:51][Step 1/2] INTERNALERROR> File "/home/teamcity/autotesting/venvs/python-tests/lib/python2.7/site-packages/_pytest/main.py", line 133, in pytest_collection
[23:35:51][Step 1/2] INTERNALERROR> return session.perform_collect()
[23:35:51][Step 1/2] INTERNALERROR> File "/home/teamcity/autotesting/venvs/python-tests/lib/python2.7/site-packages/_pytest/main.py", line 565, in perform_collect
[23:35:51][Step 1/2] INTERNALERROR> items = self._perform_collect(args, genitems)
[23:35:51][Step 1/2] INTERNALERROR> File "/home/teamcity/autotesting/venvs/python-tests/lib/python2.7/site-packages/_pytest/main.py", line 601, in _perform_collect
[23:35:51][Step 1/2] INTERNALERROR> self.items.extend(self.genitems(node))
[23:35:51][Step 1/2] INTERNALERROR> File "/home/teamcity/autotesting/venvs/python-tests/lib/python2.7/site-packages/_pytest/main.py", line 743, in genitems
[23:35:51][Step 1/2] INTERNALERROR> node.ihook.pytest_collectreport(report=rep)
[23:35:51][Step 1/2] INTERNALERROR> File "/home/teamcity/autotesting/venvs/python-tests/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
[23:35:51][Step 1/2] INTERNALERROR> return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
[23:35:51][Step 1/2] INTERNALERROR> File "/home/teamcity/autotesting/venvs/python-tests/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
[23:35:51][Step 1/2] INTERNALERROR> return self._inner_hookexec(hook, methods, kwargs)
[23:35:51][Step 1/2] INTERNALERROR> File "/home/teamcity/autotesting/venvs/python-tests/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
[23:35:51][Step 1/2] INTERNALERROR> _MultiCall(methods, kwargs, hook.spec_opts).execute()
[23:35:51][Step 1/2] INTERNALERROR> File "/home/teamcity/autotesting/venvs/python-tests/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
[23:35:51][Step 1/2] INTERNALERROR> res = hook_impl.function(*args)
[23:35:51][Step 1/2] INTERNALERROR> File "/home/teamcity/autotesting/venvs/python-tests/lib/python2.7/site-packages/teamcity_messages-1.18-py2.7.egg/teamcity/pytest_plugin.py", line 221, in pytest_collectreport
[23:35:51][Step 1/2] INTERNALERROR> self.report_test_failure(test_id, report)
[23:35:51][Step 1/2] INTERNALERROR> File "/home/teamcity/autotesting/venvs/python-tests/lib/python2.7/site-packages/teamcity_messages-1.18-py2.7.egg/teamcity/pytest_plugin.py", line 171, in report_test_failure
[23:35:51][Step 1/2] INTERNALERROR> self.report_test_output(report, test_id)
[23:35:51][Step 1/2] INTERNALERROR> File "/home/teamcity/autotesting/venvs/python-tests/lib/python2.7/site-packages/teamcity_messages-1.18-py2.7.egg/teamcity/pytest_plugin.py", line 144, in report_test_output
[23:35:51][Step 1/2] INTERNALERROR> if report.when not in secname:
[23:35:51][Step 1/2] INTERNALERROR> AttributeError: 'CollectReport' object has no attribute 'when'
```

Occured after update from teamcity-messages 1.17 to 1.18 (1.20 same result).

Teamcity version 10.0.3
platform linux2 – Python 2.7.10, pytest-2.9.0, py-1.4.31, pluggy-0.3.1
plugins: xdist-1.15.0, allure-adaptor-1.7.5, teamcity-messages-1.18

**Comment by bozhaojiangkcg** [comment]
We got same issue with teamcity-messages 1.20.

**Comment by zubchick** [comment]
same issue :(

pytest 3.0.5
teamcity-messages 1.20

**Comment by shalupov** [comment]
Fixed in 1.21
